// Generated import index. Edit knowledge/ggc records, not this file.
import type { Corpus } from './types.ts';
import products0 from '../../knowledge/ggc/products/ashwagandha-plus.json' with { type: 'json' };
import products1 from '../../knowledge/ggc/products/barbers-blend-grooming-oil.json' with { type: 'json' };
import products2 from '../../knowledge/ggc/products/charcoal-facial-cleanser.json' with { type: 'json' };
import products3 from '../../knowledge/ggc/products/charcoal-soap.json' with { type: 'json' };
import products4 from '../../knowledge/ggc/products/creatine-hydration-powder.json' with { type: 'json' };
import products5 from '../../knowledge/ggc/products/focus-powder-sour-candy.json' with { type: 'json' };
import products6 from '../../knowledge/ggc/products/gut-health.json' with { type: 'json' };
import products7 from '../../knowledge/ggc/products/hydration-powder-lychee.json' with { type: 'json' };
import products8 from '../../knowledge/ggc/products/hydration-powder-passion-fruit.json' with { type: 'json' };
import products9 from '../../knowledge/ggc/products/hydration-powder-peach-mango.json' with { type: 'json' };
import products10 from '../../knowledge/ggc/products/magnesium-glycinate.json' with { type: 'json' };
import products11 from '../../knowledge/ggc/products/nad.json' with { type: 'json' };
import products12 from '../../knowledge/ggc/products/nmn.json' with { type: 'json' };
import products13 from '../../knowledge/ggc/products/peptide-hair-growth-serum.json' with { type: 'json' };
import products14 from '../../knowledge/ggc/products/peptide-moisturizer.json' with { type: 'json' };
import products15 from '../../knowledge/ggc/products/renova-tallow-cream.json' with { type: 'json' };
import products16 from '../../knowledge/ggc/products/rich-sandalwood-soap.json' with { type: 'json' };
import products17 from '../../knowledge/ggc/products/sleep-support.json' with { type: 'json' };
import topics0 from '../../knowledge/ggc/topics/brand.json' with { type: 'json' };
import topics1 from '../../knowledge/ggc/topics/faq.json' with { type: 'json' };
import topics2 from '../../knowledge/ggc/topics/founder.json' with { type: 'json' };
import topics3 from '../../knowledge/ggc/topics/governance.json' with { type: 'json' };
import topics4 from '../../knowledge/ggc/topics/pillars.json' with { type: 'json' };
import topics5 from '../../knowledge/ggc/topics/reserve.json' with { type: 'json' };
import topics6 from '../../knowledge/ggc/topics/safety.json' with { type: 'json' };
import topics7 from '../../knowledge/ggc/topics/sales.json' with { type: 'json' };
import topics8 from '../../knowledge/ggc/topics/sanctum.json' with { type: 'json' };
import topics9 from '../../knowledge/ggc/topics/voice.json' with { type: 'json' };
import topics10 from '../../knowledge/ggc/topics/wellness.json' with { type: 'json' };
import topics11 from '../../knowledge/ggc/topics/wholesale.json' with { type: 'json' };
import sources from '../../knowledge/ggc/sources/registry.json' with { type: 'json' };
import issues from '../../knowledge/ggc/issues/open.json' with { type: 'json' };
export const corpus = { version: '2026-09-05.1', reviewedAt: '2026-09-05', products: [products0,products1,products2,products3,products4,products5,products6,products7,products8,products9,products10,products11,products12,products13,products14,products15,products16,products17], topics: [topics0,topics1,topics2,topics3,topics4,topics5,topics6,topics7,topics8,topics9,topics10,topics11], sources, issues } as Corpus;
